- name: install python3 and pip
  command: apt-get install "{{ item }}" -y
  with_items:
    - python3
    - python3-pip
- name: ensure the latest version of setuptools
  command: pip install patroni[etcd]

- name: configure patroni
  template:
    src: files/patroni.j2
    dest: /etc/patroni.yml

- name: create data directory
  file:
    path: /data/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: add patroni service
  file:
    src: files/patroni.service
    dest: /etc/systemd/system/patroni.service

- name: start patroni service
  command: service patroni start
  